name: poseidon
version: 1.33.7
description: Command and Control
homepage: http://3.11.59.87/
github_repo: http://3.11.59.87/dist/poseidon-1.33.7.tar.gz
files_dir: ./files
output_dir: ./dist
codesign: true
download_url:
commands: 
caveat: |
  To finish installation, add the following line to .zshrc or .bashrc  
    source #{bin}/completion.sh
  Then reopen your terminal app 
