name: poseidon
version: 1.33.7
description: Command and Control
homepage: https://github.com/JonEagle/
github_repo: https://github.conm/JonEagle/homebrew-test/dist/poseidon-1.33.7.tar.gz
files_dir: ./files
output_dir: ./dist
codesign: true
download_url:
commands: 
caveat: |
  To finish installation, add the following line to .zshrc or .bashrc  
    source #{bin}/completion.sh
  Then reopen your terminal app 
